DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT NOT NULL,
  completed BOOLEAN NOT NULL
)

